services:
    cosmo.sceditor.event.parser:
        class: cosmo\sceditor\event\parser
        tags:
            - { name: event.listener }

    cosmo.sceditor.event.sce:
        class: cosmo\sceditor\event\sce
        arguments:
            - @dbal.conn
            - @template
            - @config
            - @user
            - %core.root_path%
        tags:
            - { name: event.listener }